name: CI

on: [push, pull_request]

jobs:
  test:
    name: Node.js v${{ matrix.nodejs }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodejs: [10, 12]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.nodejs }}

    # https://github.com/microsoft/playwright/blob/master/docs/ci.md#directories-to-cache
    - name: (env) cache
      uses: actions/cache@master
      with:
        path: |
          node_modules
          */*/node_modules
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}

    - name: Install
      run: |
        npm install
        npm install -g nyc

    - name: Test w/ Coverage
      run: nyc --include=src npm test

    - name: Report
      if: matrix.nodejs >= 12
      run: |
        nyc report --reporter=text-lcov > coverage.lcov
        bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
